"""empty message

Revision ID: 670ff9806bc5
Revises: 7fd7fc347bc5
Create Date: 2025-04-24 15:22:34.020345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670ff9806bc5'
down_revision = '7fd7fc347bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activities', schema=None) as batch_op:
        batch_op.drop_column('start_entry_id')
        batch_op.drop_column('end_entry_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_entry_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('start_entry_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
