"""Add CurrentActivities table

Revision ID: 6e9df555cbcd
Revises: 
Create Date: 2025-04-22 16:36:08.125260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9df555cbcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_entry_id', sa.Integer(), nullable=False),
    sa.Column('end_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_entry_id'], ['media_entries.id'], ),
    sa.ForeignKeyConstraint(['start_entry_id'], ['media_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_activities')
    # ### end Alembic commands ###
