"""Add SharedUsers table and modify Activities and Entries tables

Revision ID: 893d602f6a14
Revises: 0dbeff44d6ae
Create Date: 2025-04-27 23:16:29.260931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893d602f6a14'
down_revision = '0dbeff44d6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SharedUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('shared_username', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['shared_username'], ['Users.username'], ),
    sa.ForeignKeyConstraint(['username'], ['Users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('media_name', sa.String(length=120), nullable=False))

    with op.batch_alter_table('Entries', schema=None) as batch_op:
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_name', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('media_type', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('Activities', schema=None) as batch_op:
        batch_op.drop_column('media_name')
        batch_op.drop_column('media_type')

    op.drop_table('SharedUsers')
    # ### end Alembic commands ###
