"""changed duration to Integer type, added rating & comment attribute to activities table, ensure consistency of naming conventions

Revision ID: bbafb28dcf75
Revises: 6e9df555cbcd
Create Date: 2025-04-23 15:53:34.887422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbafb28dcf75'
down_revision = '6e9df555cbcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    with op.batch_alter_table('media_entries', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_entries', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('current_activities', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
