"""added sub-type to Activities table

Revision ID: e6a86ae0f14f
Revises: 893d602f6a14
Create Date: 2025-04-28 22:50:14.582640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a86ae0f14f'
down_revision = '893d602f6a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_subtype', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activities', schema=None) as batch_op:
        batch_op.drop_column('media_subtype')

    # ### end Alembic commands ###
